### ISSUE TITLE
es 5.14

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/random#2]
![es5_14](https://cloud.githubusercontent.com/assets/3002194/15456340/56db19f8-206d-11e6-84da-65ea56ee8803.png)

**Comment by FabioZTessitore** [comment]
non sembrava difficile

**Comment by Teodoro777** [comment]
Ma infatti non ho ancora provato nulla, astento ho letto il problema.. Vedo di fare qualcosa stasera

**Comment by Teodoro777** [comment]
Appena possibile vi collegate e mi fate capire come fare questo stupido programma? ahaha

**Comment by FabioZTessitore** [comment]
Sei capace di estrarre un numero compreso in un intervallo? Ad esempio tra
15 e 76

Il martedì 31 maggio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Certo

**Comment by FabioZTessitore** [comment]
Bene. Allora trova l'intervallo giusto e troverai la soluzione

Il martedì 31 maggio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ma adesso non sono numeri continui

**Comment by FabioZTessitore** [comment]
Lo so. Trova l'intervallo giusto

Il martedì 31 maggio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
il punto c non va bene. Lo hai testato?

**Comment by Teodoro777** [comment]
L'ho testato più volte.. Forse sono stato fortunato ahah

**Comment by FabioZTessitore** [comment]
Esecuzione 9 volte. Ben 2 esce un numero non in lista

![random_c](https://cloud.githubusercontent.com/assets/3002194/15783619/31f5ee38-29af-11e6-9d01-37dab0c6e5fb.png)
